// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvjwyicnjtexrbokvedb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2and5aWNuanRleHJib2t2ZWRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NDkwNTksImV4cCI6MjA2NjMyNTA1OX0.QQmur21BnljF_HsKsSSvLk6fHe6bV8gJJyke3BBn2WE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);